name: CI for Laravel and React

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: mbstring, pdo_mysql

    - name: Install Composer dependencies
      run: composer install --no-scripts --no-interaction --prefer-dist

    - name: Run Laravel tests
      run: php artisan test

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install and build React
      run: |
        cd frontend
        npm install
        npm run build
